"""
Full ManagerBasedRLEnv configuration for quadruped flat-terrain locomotion.

The robot learns to track commanded (vx, vy, wz) velocity using a position-
target action space over all 12 joints. Observations are proprioceptive only
(no vision) to match what will be available on hardware.

Scene
-----
  base_link (body)
  └─ 4× hip → thigh → shin → foot_link  (12 revolute + 4 fixed joints)
  contact_forces sensor on all four foot_links
  IMU sensor on base_link

Obs (48-dim)
------------
  base linear velocity   [3]   body frame, noisy
  base angular velocity  [3]   body frame, noisy
  projected gravity      [3]   body frame, noisy
  velocity command       [3]   (vx, vy, wz), ground-truth
  joint pos − default    [12]  noisy
  joint velocities       [12]  noisy
  last action            [12]  clean

Actions (12-dim)
----------------
  joint position offsets from the default standing pose, clipped to ±0.5 rad.
  Isaac Lab's ImplicitActuator converts these targets to torques via PD control.
"""
from __future__ import annotations

import math
import os
from pathlib import Path

import isaaclab.envs.mdp as mdp
import isaaclab.sim as sim_utils
from isaaclab.assets import ArticulationCfg, AssetBaseCfg
from isaaclab.envs import ManagerBasedRLEnvCfg
from isaaclab.managers import (
    EventTermCfg,
    ObservationGroupCfg,
    ObservationTermCfg,
    RewardTermCfg,
    SceneEntityCfg,
    TerminationTermCfg,
)
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sensors import ContactSensorCfg
from isaaclab.utils import configclass
from isaaclab.utils.noise import AdditiveUniformNoiseCfg as Unoise

# ── Asset path ────────────────────────────────────────────────────────────────
# Generated by:  python scripts/generate_urdf.py → scripts/convert_to_usd.sh
_ASSETS_DIR = Path(__file__).resolve().parents[3] / "assets" / "quadruped"
QUADRUPED_USD_PATH = str(_ASSETS_DIR / "quadruped.usd")

# ── Default standing joint angles (rad) ──────────────────────────────────────
# Derived from IK with foot target at (0, ±0.162, −0.30) in body frame.
# Hip=0°, Thigh=+36.9° (0.644 rad), Knee=−77° (−1.345 rad).
_STAND_HIP   =  0.000
_STAND_THIGH =  0.644
_STAND_KNEE  = -1.345


# ── Scene ─────────────────────────────────────────────────────────────────────

@configclass
class QuadrupedSceneCfg(InteractiveSceneCfg):
    """Everything that exists in the simulation world."""

    ground = AssetBaseCfg(
        prim_path="/World/defaultGroundPlane",
        spawn=sim_utils.GroundPlaneCfg(),
    )

    dome_light = AssetBaseCfg(
        prim_path="/World/Light",
        spawn=sim_utils.DomeLightCfg(intensity=3000.0, color=(0.75, 0.75, 0.75)),
    )

    robot: ArticulationCfg = ArticulationCfg(
        prim_path="{ENV_REGEX_NS}/Robot",
        spawn=sim_utils.UsdFileCfg(
            usd_path=QUADRUPED_USD_PATH,
            activate_contact_sensors=True,
            rigid_props=sim_utils.RigidBodyPropertiesCfg(
                disable_gravity=False,
                retain_accelerations=False,
                linear_damping=0.0,
                angular_damping=0.0,
                max_linear_velocity=1000.0,
                max_angular_velocity=1000.0,
                max_depenetration_velocity=1.0,
            ),
            articulation_props=sim_utils.ArticulationRootPropertiesCfg(
                enabled_self_collisions=False,
                solver_position_iteration_count=4,
                solver_velocity_iteration_count=0,
            ),
        ),
        init_state=ArticulationCfg.InitialStateCfg(
            # z=0.36m: body centre above ground at nominal standing height (0.32m) + 0.04m margin
            pos=(0.0, 0.0, 0.36),
            joint_pos={
                "FL_hip_joint":   _STAND_HIP,   "FR_hip_joint":   _STAND_HIP,
                "RL_hip_joint":   _STAND_HIP,   "RR_hip_joint":   _STAND_HIP,
                "FL_thigh_joint": _STAND_THIGH, "FR_thigh_joint": _STAND_THIGH,
                "RL_thigh_joint": _STAND_THIGH, "RR_thigh_joint": _STAND_THIGH,
                "FL_knee_joint":  _STAND_KNEE,  "FR_knee_joint":  _STAND_KNEE,
                "RL_knee_joint":  _STAND_KNEE,  "RR_knee_joint":  _STAND_KNEE,
            },
            joint_vel={".*": 0.0},
        ),
        actuators={
            # QDD motors modelled as implicit PD controllers.
            # Kp=25 N·m/rad, Kd=0.5 N·m·s/rad is typical for lightweight QDD legs.
            "legs": ImplicitActuatorCfg(
                joint_names_expr=[".*_hip_joint", ".*_thigh_joint", ".*_knee_joint"],
                effort_limit=20.0,
                velocity_limit=20.0,
                stiffness=25.0,
                damping=0.5,
            ),
        },
    )

    # Contact sensors on shin links — foot_link was merged into shin_link by --merge-joints.
    contact_forces = ContactSensorCfg(
        prim_path="{ENV_REGEX_NS}/Robot/.*_shin_link",
        history_length=3,
        track_air_time=True,
    )


# ── Observations ──────────────────────────────────────────────────────────────

@configclass
class ObservationsCfg:
    """48-dimensional proprioceptive observation vector."""

    @configclass
    class PolicyCfg(ObservationGroupCfg):
        # Body state — all in the base (robot) frame
        base_lin_vel = ObservationTermCfg(
            func=mdp.base_lin_vel,
            noise=Unoise(n_min=-0.1, n_max=0.1),
        )
        base_ang_vel = ObservationTermCfg(
            func=mdp.base_ang_vel,
            noise=Unoise(n_min=-0.2, n_max=0.2),
        )
        projected_gravity = ObservationTermCfg(
            func=mdp.projected_gravity,
            noise=Unoise(n_min=-0.05, n_max=0.05),
        )
        # Commanded velocity — no noise (it's the target we're trying to track)
        velocity_commands = ObservationTermCfg(
            func=mdp.generated_commands,
            params={"command_name": "base_velocity"},
        )
        # Joint state relative to the default standing pose
        joint_pos = ObservationTermCfg(
            func=mdp.joint_pos_rel,
            noise=Unoise(n_min=-0.01, n_max=0.01),
        )
        joint_vel = ObservationTermCfg(
            func=mdp.joint_vel_rel,
            noise=Unoise(n_min=-1.5, n_max=1.5),
        )
        # Previous action (helps the policy be temporally consistent)
        actions = ObservationTermCfg(func=mdp.last_action)

        def __post_init__(self) -> None:
            self.enable_corruption = True
            self.concatenate_terms = True

    policy: PolicyCfg = PolicyCfg()


# ── Actions ───────────────────────────────────────────────────────────────────

@configclass
class ActionsCfg:
    """12-D joint position targets (offset from default standing pose)."""

    joint_pos = mdp.JointPositionActionCfg(
        asset_name="robot",
        joint_names=[".*_hip_joint", ".*_thigh_joint", ".*_knee_joint"],
        scale=0.5,           # NN output ∈ [−1,+1] → joint offset ∈ [−0.5, +0.5] rad
        use_default_offset=True,
    )


# ── Commands ──────────────────────────────────────────────────────────────────

@configclass
class CommandsCfg:
    """Random body-velocity commands resampled every 10 s."""

    base_velocity = mdp.UniformVelocityCommandCfg(
        asset_name="robot",
        resampling_time_range=(10.0, 10.0),
        rel_standing_envs=0.02,     # 2 % of envs commanded to stand still
        rel_heading_envs=1.0,
        heading_command=True,
        heading_control_stiffness=0.5,
        debug_vis=True,
        ranges=mdp.UniformVelocityCommandCfg.Ranges(
            lin_vel_x=(-1.0, 1.0),
            lin_vel_y=(-0.5, 0.5),
            ang_vel_z=(-1.0, 1.0),
            heading=(-math.pi, math.pi),
        ),
    )


# ── Rewards ───────────────────────────────────────────────────────────────────

@configclass
class RewardsCfg:
    """
    Reward shaping for locomotion.

    Primary objective: track the commanded (vx, vy, wz).
    Everything else is a penalty that discourages bad strategies (bouncing,
    high energy use, bad posture, or falling).

    Weights are tuned for a ~5 kg robot. Scale all weights together if
    the reward is too noisy to converge.
    """

    # ── Primary: velocity tracking ────────────────────────────────────────────
    track_lin_vel_xy_exp = RewardTermCfg(
        func=mdp.track_lin_vel_xy_exp,
        weight=1.0,
        params={"command_name": "base_velocity", "std": math.sqrt(0.25)},
    )
    track_ang_vel_z_exp = RewardTermCfg(
        func=mdp.track_ang_vel_z_exp,
        weight=0.5,
        params={"command_name": "base_velocity", "std": math.sqrt(0.25)},
    )

    # ── Stability penalties ───────────────────────────────────────────────────
    lin_vel_z_l2 = RewardTermCfg(func=mdp.lin_vel_z_l2, weight=-2.0)
    ang_vel_xy_l2 = RewardTermCfg(func=mdp.ang_vel_xy_l2, weight=-0.05)
    flat_orientation_l2 = RewardTermCfg(func=mdp.flat_orientation_l2, weight=-2.0)

    # ── Joint health penalties ────────────────────────────────────────────────
    joint_pos_limits = RewardTermCfg(func=mdp.joint_pos_limits, weight=-1.0)
    joint_vel_limits = RewardTermCfg(
        func=mdp.joint_vel_limits,
        weight=-1.0,
        params={"soft_ratio": 0.9},
    )
    joint_torques_l2 = RewardTermCfg(
        func=mdp.joint_torques_l2, weight=-1.0e-5
    )
    joint_acc_l2 = RewardTermCfg(func=mdp.joint_acc_l2, weight=-2.5e-7)
    action_rate_l2 = RewardTermCfg(func=mdp.action_rate_l2, weight=-0.01)

    # ── Gait quality ──────────────────────────────────────────────────────────
    # feet_air_time disabled: mdp.feet_air_time was removed in isaaclab 2.3.x.
    # Re-enable once the replacement function name is confirmed (grep rewards.py).
    # Penalise contacts on shin or thigh (robot should only touch ground with feet).
    undesired_contacts = RewardTermCfg(
        func=mdp.undesired_contacts,
        weight=-1.0,
        params={
            "sensor_cfg": SceneEntityCfg(
                "contact_forces",
                body_names=[".*_thigh_link"],
            ),
            "threshold": 1.0,
        },
    )


# ── Terminations ──────────────────────────────────────────────────────────────

@configclass
class TerminationsCfg:
    """Episode ends on timeout or if the body touches the ground."""

    time_out = TerminationTermCfg(func=mdp.time_out, time_out=True)

    # Body contact → robot has fallen
    base_contact = TerminationTermCfg(
        func=mdp.illegal_contact,
        params={
            "sensor_cfg": SceneEntityCfg("contact_forces", body_names="base_link"),
            "threshold": 1.0,
        },
    )


# ── Events (domain randomisation) ────────────────────────────────────────────

@configclass
class EventCfg:
    """
    Domain randomisation for sim-to-real transfer.

    Startup events fire once when the env is created.
    Reset events fire at the start of every episode.
    Interval events fire periodically during an episode.
    """

    # Randomise floor friction — the biggest sim-to-real gap for locomotion.
    physics_material = EventTermCfg(
        func=mdp.randomize_rigid_body_material,
        mode="startup",
        params={
            "asset_cfg": SceneEntityCfg("robot", body_names=".*"),
            "static_friction_range": (0.4, 0.9),
            "dynamic_friction_range": (0.4, 0.9),
            "restitution_range": (0.0, 0.0),
            "num_buckets": 64,
        },
    )

    # ±0.5 kg payload variation (simulates carrying a sensor package)
    add_base_mass = EventTermCfg(
        func=mdp.randomize_rigid_body_mass,
        mode="startup",
        params={
            "asset_cfg": SceneEntityCfg("robot", body_names="base_link"),
            "mass_distribution_params": (-0.5, 0.5),
            "operation": "add",
        },
    )

    # Random initial pose at episode start (position + yaw, small velocity)
    reset_base = EventTermCfg(
        func=mdp.reset_root_state_uniform,
        mode="reset",
        params={
            "pose_range": {"x": (-0.5, 0.5), "y": (-0.5, 0.5), "yaw": (-math.pi, math.pi)},
            "velocity_range": {
                "x": (-0.2, 0.2), "y": (-0.2, 0.2), "z": (-0.1, 0.1),
                "roll": (-0.2, 0.2), "pitch": (-0.2, 0.2), "yaw": (-0.2, 0.2),
            },
        },
    )

    # Randomise joint start angles (keeps the policy robust to leg positions)
    reset_robot_joints = EventTermCfg(
        func=mdp.reset_joints_by_scale,
        mode="reset",
        params={"position_range": (0.85, 1.15), "velocity_range": (0.0, 0.0)},
    )

    # Random push every 10–15 s (tests balance recovery)
    push_robot = EventTermCfg(
        func=mdp.push_by_setting_velocity,
        mode="interval",
        interval_range_s=(10.0, 15.0),
        params={"velocity_range": {"x": (-0.5, 0.5), "y": (-0.5, 0.5)}},
    )


# ── Top-level environment config ──────────────────────────────────────────────

@configclass
class QuadrupedFlatEnvCfg(ManagerBasedRLEnvCfg):
    """
    Flat-terrain locomotion environment for the 5 kg quadruped.

    Key timing:
      sim.dt      = 0.005 s  → physics at 200 Hz
      decimation  = 4        → policy runs at  50 Hz
      episode     = 20 s     → 1000 policy steps per episode
    """

    scene:        QuadrupedSceneCfg  = QuadrupedSceneCfg(num_envs=32, env_spacing=2.5)
    observations: ObservationsCfg   = ObservationsCfg()
    actions:      ActionsCfg        = ActionsCfg()
    commands:     CommandsCfg       = CommandsCfg()
    rewards:      RewardsCfg        = RewardsCfg()
    terminations: TerminationsCfg   = TerminationsCfg()
    events:       EventCfg          = EventCfg()

    def __post_init__(self) -> None:
        super().__post_init__()

        # Physics rate
        self.sim.dt = 0.005            # 200 Hz
        self.decimation = 4            # policy at 50 Hz
        self.episode_length_s = 20.0

        # Viewer camera angle (useful when not running headless)
        self.viewer.resolution = (1280, 720)
        self.viewer.eye = (3.5, 3.5, 2.5)
        self.viewer.lookat = (0.0, 0.0, 0.5)

        # Simulation settings
        self.sim.gravity = (0.0, 0.0, -9.81)
        self.sim.render_interval = self.decimation

        if self.scene.contact_forces is not None:
            self.scene.contact_forces.update_period = self.sim.dt
