"""
Full ManagerBasedRLEnv configuration for quadruped flat-terrain locomotion.

V6: a faithful port of Isaac Lab's own Unitree Go2 flat-terrain velocity task
(isaaclab_tasks/manager_based/locomotion/velocity + config/go2, read at the
v2.3.2 tag — the exact version this project pins), cross-checked against
legged_gym's A1 config. Walking quadrupeds are a solved problem; V3-V5 kept
inventing reward terms and thresholds on top of a half-matched port and got a
creep every time. V6's rule: match the reference exactly, and deviate only
where this robot's geometry genuinely differs — with the reason written down.

What V3-V5 got wrong (all verified against reference source, not assumed):

  * `feet_air_time` threshold. V3 used 0.3s, V4 "root-caused" the creep to
    that threshold taxing walking and cut it to 0.15s. The reference uses
    **0.5s** — higher than the value V4 called the bug — with weight 0.25
    (we had 1.0, 4x too high). The V4 analysis was backwards: this term is a
    small regulariser in every working config, not the engine of gait.
  * Extra invented terms. `joint_deviation_hip_l1` (-0.2, always-on, directly
    penalising the hip motion a gait needs), `stand_still_joint_deviation_l1`,
    `feet_air_time_variance` (-1.0, reconstructed from an unverifiable source),
    `joint_vel_l2`, plus a hand-rolled command curriculum. None exist in Go2
    flat. Every one was a confound; all are gone.
  * Ground friction. We randomised static/dynamic over (0.4, 0.9) — the low
    end is a genuinely slippery floor, which makes the planted-foot glide
    *physically cheap*. The reference uses fixed 0.8 static / 0.6 dynamic.
    This is probably the single biggest enabler of the creep.
  * Default stance. Ours stood nearly straight-legged (thigh 0.644, knee
    -1.345). Every Unitree reference stands deeply crouched (thigh 0.8,
    calf -1.5). With `use_default_offset=True` and action scale 0.25, actions
    are offsets *from this pose* — from a straight-legged stance ±0.25 rad
    cannot produce a real swing, so the policy physically could not step even
    if the reward said to.
  * `undesired_contacts` covered thigh **and shin**. The reference covers
    thigh only (Go2 disables it outright). Penalising shin contact discourages
    the deep leg flexion a real gait needs.
  * `soft_joint_pos_limit_factor` was never set (defaults to 1.0). Every
    Unitree reference sets 0.9.

Scene
-----
  base_link (body)
  └─ 4x hip -> thigh -> shin -> foot_link  (12 revolute + 4 fixed joints)
  contact_forces sensor on all four foot_links
  IMU sensor on base_link

Obs (48-dim)
------------
  base linear velocity   [3]   body frame, noisy
  base angular velocity  [3]   body frame, noisy
  projected gravity      [3]   body frame, noisy
  velocity command       [3]   (vx, vy, wz), ground-truth
  joint pos - default    [12]  noisy
  joint velocities       [12]  noisy
  last action            [12]  clean
  (noise magnitudes verified as an exact match to the reference config)

Actions (12-dim)
----------------
  joint position offsets from the default standing pose, scaled 0.25
  (Go2's own override of the generic 0.5 default).
"""
from __future__ import annotations

import math
from pathlib import Path

import isaaclab.envs.mdp as mdp
import isaaclab.sim as sim_utils
from isaaclab.actuators import DCMotorCfg
from isaaclab.assets import ArticulationCfg, AssetBaseCfg
from isaaclab.envs import ManagerBasedRLEnvCfg
from isaaclab.managers import (
    EventTermCfg,
    ObservationGroupCfg,
    ObservationTermCfg,
    RewardTermCfg,
    SceneEntityCfg,
    TerminationTermCfg,
)
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sensors import ContactSensorCfg
from isaaclab.utils import configclass
from isaaclab.utils.noise import AdditiveUniformNoiseCfg as Unoise

from src.simulation.isaac_lab import mdp as gait_mdp

# ── Asset path ────────────────────────────────────────────────────────────────
# Generated by:  python scripts/generate_urdf.py → scripts/convert_to_usd.sh
_ASSETS_DIR = Path(__file__).resolve().parents[3] / "assets" / "quadruped"
QUADRUPED_USD_PATH = str(_ASSETS_DIR / "quadruped.usd")

# ── Default standing joint angles (rad) ──────────────────────────────────────
# V6: adopted from UNITREE_GO2_CFG / UNITREE_A1_CFG / UNITREE_GO1_CFG, which
# all share thigh=0.8, calf=-1.5 — a deeply crouched stance. V3-V5 used an
# IK-derived near-straight pose (thigh 0.644, knee -1.345) that left almost no
# usable swing range within the +-0.25 rad action window.
#
# Two deliberate deviations from the Unitree numbers, both geometry-driven:
#   * Hip stays 0.0, not the reference +-0.1. The reference splays the legs
#     outward, but that sign convention is tied to Unitree's hip axis
#     orientation; this URDF's convention (positive = adduction, i.e. inward,
#     per config/robot_params.yaml) is not verified to match, and a wrong sign
#     would pull the legs *together* under the body. 0.0 is neutral in either
#     convention.
#   * Front and rear thighs both use 0.8. Unitree tucks the rear legs harder
#     (front 0.8 / rear 1.0) because their legs mount asymmetrically; this
#     robot's URDF is generated symmetrically from robot_params.yaml, so
#     copying that asymmetry would just pitch the body nose-up.
_STAND_HIP   =  0.000
_STAND_THIGH =  0.800
_STAND_KNEE  = -1.500

# Resulting stance height, from this robot's link lengths (l_thigh=0.209,
# l_shin=0.195, shin length already runs to the foot contact point):
#   0.209*cos(0.8) + 0.195*cos(0.8-1.5) = 0.146 + 0.149 = 0.295 m
# Spawn just above it so the robot settles onto its feet rather than dropping.
_INIT_HEIGHT = 0.34


# ── Scene ─────────────────────────────────────────────────────────────────────

@configclass
class QuadrupedSceneCfg(InteractiveSceneCfg):
    """Everything that exists in the simulation world."""

    ground = AssetBaseCfg(
        prim_path="/World/defaultGroundPlane",
        spawn=sim_utils.GroundPlaneCfg(),
    )

    dome_light = AssetBaseCfg(
        prim_path="/World/Light",
        spawn=sim_utils.DomeLightCfg(intensity=3000.0, color=(0.75, 0.75, 0.75)),
    )

    robot: ArticulationCfg = ArticulationCfg(
        prim_path="{ENV_REGEX_NS}/Robot",
        spawn=sim_utils.UsdFileCfg(
            usd_path=QUADRUPED_USD_PATH,
            activate_contact_sensors=True,
            rigid_props=sim_utils.RigidBodyPropertiesCfg(
                disable_gravity=False,
                retain_accelerations=False,
                linear_damping=0.0,
                angular_damping=0.0,
                max_linear_velocity=1000.0,
                max_angular_velocity=1000.0,
                max_depenetration_velocity=1.0,
            ),
            articulation_props=sim_utils.ArticulationRootPropertiesCfg(
                enabled_self_collisions=False,
                solver_position_iteration_count=4,
                solver_velocity_iteration_count=0,
            ),
        ),
        # 0.9, matching every Unitree reference cfg. Never set before V6, so it
        # defaulted to 1.0 — meaning the `dof_pos_limits` penalty below only
        # fired at the true hard limit instead of 10% short of it, i.e. it was
        # very nearly a no-op (it logged ~-0.0001 all through the V5 run).
        soft_joint_pos_limit_factor=0.9,
        init_state=ArticulationCfg.InitialStateCfg(
            pos=(0.0, 0.0, _INIT_HEIGHT),
            joint_pos={
                "FL_hip_joint":   _STAND_HIP,   "FR_hip_joint":   _STAND_HIP,
                "RL_hip_joint":   _STAND_HIP,   "RR_hip_joint":   _STAND_HIP,
                "FL_thigh_joint": _STAND_THIGH, "FR_thigh_joint": _STAND_THIGH,
                "RL_thigh_joint": _STAND_THIGH, "RR_thigh_joint": _STAND_THIGH,
                "FL_knee_joint":  _STAND_KNEE,  "FR_knee_joint":  _STAND_KNEE,
                "RL_knee_joint":  _STAND_KNEE,  "RR_knee_joint":  _STAND_KNEE,
            },
            joint_vel={".*": 0.0},
        ),
        actuators={
            # V6: DCMotorCfg, not ImplicitActuatorCfg — Go2 and A1 both use it.
            # It models the DC torque-speed curve, so available torque falls off
            # as joint speed rises. That realism matters here specifically: an
            # implicit PD actuator delivers full torque at any velocity, which
            # makes holding a rigid static creep pose unrealistically cheap.
            # stiffness=25.0 / damping=0.5 are the reference Go2/A1 gains and
            # happen to already match what this config used.
            # effort/velocity limits stay this robot's own (10 N.m hip,
            # 20 N.m thigh+knee, 20 rad/s) from config/robot_params.yaml rather
            # than Go2's 23.5 N.m / 30 rad/s — those are hardware facts about
            # this design, not tuning knobs. saturation_effort mirrors
            # effort_limit, as in the reference.
            "hips": DCMotorCfg(
                joint_names_expr=[".*_hip_joint"],
                effort_limit=10.0,
                saturation_effort=10.0,
                velocity_limit=20.0,
                stiffness=25.0,
                damping=0.5,
                friction=0.0,
            ),
            "legs": DCMotorCfg(
                joint_names_expr=[".*_thigh_joint", ".*_knee_joint"],
                effort_limit=20.0,
                saturation_effort=20.0,
                velocity_limit=20.0,
                stiffness=25.0,
                damping=0.5,
                friction=0.0,
            ),
        },
    )

    # Contact sensors on all robot bodies — rewards/terminations filter by body_names.
    # foot_link is its own rigid body (not merged into shin_link), so a real
    # foot strike and shin/knee dragging show up as distinct contacts.
    contact_forces = ContactSensorCfg(
        prim_path="{ENV_REGEX_NS}/Robot/.*",
        history_length=3,
        track_air_time=True,
    )


# ── Observations ──────────────────────────────────────────────────────────────

@configclass
class ObservationsCfg:
    """48-dimensional proprioceptive observation vector.

    Verified byte-for-byte against the reference velocity task's policy
    observation group (minus the height scanner, which is rough-terrain only):
    same terms, same order, same noise magnitudes. Unchanged in V6.
    """

    @configclass
    class PolicyCfg(ObservationGroupCfg):
        # Body state — all in the base (robot) frame
        base_lin_vel = ObservationTermCfg(
            func=mdp.base_lin_vel,
            noise=Unoise(n_min=-0.1, n_max=0.1),
        )
        base_ang_vel = ObservationTermCfg(
            func=mdp.base_ang_vel,
            noise=Unoise(n_min=-0.2, n_max=0.2),
        )
        projected_gravity = ObservationTermCfg(
            func=mdp.projected_gravity,
            noise=Unoise(n_min=-0.05, n_max=0.05),
        )
        # Commanded velocity — no noise (it's the target we're trying to track)
        velocity_commands = ObservationTermCfg(
            func=mdp.generated_commands,
            params={"command_name": "base_velocity"},
        )
        # Joint state relative to the default standing pose
        joint_pos = ObservationTermCfg(
            func=mdp.joint_pos_rel,
            noise=Unoise(n_min=-0.01, n_max=0.01),
        )
        joint_vel = ObservationTermCfg(
            func=mdp.joint_vel_rel,
            noise=Unoise(n_min=-1.5, n_max=1.5),
        )
        # Previous action (helps the policy be temporally consistent)
        actions = ObservationTermCfg(func=mdp.last_action)

        def __post_init__(self) -> None:
            self.enable_corruption = True
            self.concatenate_terms = True

    policy: PolicyCfg = PolicyCfg()


# ── Actions ───────────────────────────────────────────────────────────────────

@configclass
class ActionsCfg:
    """12-D joint position targets (offset from default standing pose)."""

    joint_pos = mdp.JointPositionActionCfg(
        asset_name="robot",
        joint_names=[".*_hip_joint", ".*_thigh_joint", ".*_knee_joint"],
        # 0.25 — Go2's own override of the generic 0.5, and legged_gym A1's
        # value too. Unchanged from V5; this was already correct. What changed
        # is the pose it offsets *from* (see _STAND_THIGH above): the same
        # +-0.25 rad window is far more useful from a crouched stance.
        scale=0.25,
        use_default_offset=True,
    )


# ── Commands ──────────────────────────────────────────────────────────────────

@configclass
class CommandsCfg:
    """Random body-velocity commands resampled every 10 s.

    Reference values throughout: +-1.0 on all three axes. V3-V5 narrowed
    lin_vel_y to +-0.5 on the reasoning that lateral gait is harder for a
    0.2 m-wide robot — but the reference asks +-1.0 of Go2 and gets it, so
    that narrowing was unjustified caution. V5's velocity-command curriculum
    is gone: no reference flat-terrain config ramps command ranges, and it
    demonstrably did not break the creep (the V5 run reached full range at
    iteration ~1010 and the policy simply glided faster).
    """

    base_velocity = mdp.UniformVelocityCommandCfg(
        asset_name="robot",
        resampling_time_range=(10.0, 10.0),
        rel_standing_envs=0.02,
        rel_heading_envs=1.0,
        heading_command=True,
        heading_control_stiffness=0.5,
        debug_vis=True,
        ranges=mdp.UniformVelocityCommandCfg.Ranges(
            lin_vel_x=(-1.0, 1.0),
            lin_vel_y=(-1.0, 1.0),
            ang_vel_z=(-1.0, 1.0),
            heading=(-math.pi, math.pi),
        ),
    )


# ── Rewards ───────────────────────────────────────────────────────────────────

@configclass
class RewardsCfg:
    """
    Reward shaping for locomotion — a direct port of Isaac Lab's Go2 flat
    config (velocity_env_cfg.py base + config/go2 overrides, at v2.3.2).

    The full reference term list is exactly: two tracking rewards, five
    stability/effort penalties, feet_air_time, undesired_contacts,
    flat_orientation_l2, dof_pos_limits. That's it. Everything V3-V5 added on
    top has been removed — see the module docstring.
    """

    # ── Primary: velocity tracking (Go2 override of the 1.0/0.5 base) ────────
    track_lin_vel_xy_exp = RewardTermCfg(
        func=mdp.track_lin_vel_xy_exp,
        weight=1.5,
        params={"command_name": "base_velocity", "std": math.sqrt(0.25)},
    )
    track_ang_vel_z_exp = RewardTermCfg(
        func=mdp.track_ang_vel_z_exp,
        weight=0.75,
        params={"command_name": "base_velocity", "std": math.sqrt(0.25)},
    )

    # ── Stability penalties ───────────────────────────────────────────────────
    lin_vel_z_l2 = RewardTermCfg(func=mdp.lin_vel_z_l2, weight=-2.0)
    ang_vel_xy_l2 = RewardTermCfg(func=mdp.ang_vel_xy_l2, weight=-0.05)
    # -2.5 is the Go2/A1 *flat* override (the shared base leaves it at 0.0).
    flat_orientation_l2 = RewardTermCfg(func=mdp.flat_orientation_l2, weight=-2.5)

    # ── Joint health penalties ────────────────────────────────────────────────
    # -2e-4: Go2's override, and legged_gym A1's `torques` scale. Correct since V5.
    joint_torques_l2 = RewardTermCfg(func=mdp.joint_torques_l2, weight=-2.0e-4)
    joint_acc_l2 = RewardTermCfg(func=mdp.joint_acc_l2, weight=-2.5e-7)
    action_rate_l2 = RewardTermCfg(func=mdp.action_rate_l2, weight=-0.01)
    # -10.0 from legged_gym A1 (Isaac Lab's own configs leave this at 0.0).
    # Only meaningful now that soft_joint_pos_limit_factor=0.9 is set on the
    # articulation — legged_gym pairs this weight with soft_dof_pos_limit=0.9.
    dof_pos_limits = RewardTermCfg(func=mdp.joint_pos_limits, weight=-10.0)

    # ── Gait quality ──────────────────────────────────────────────────────────
    # Reference values: weight 0.25 (Go2/A1 flat), threshold 0.5s.
    # V3 ran 0.3s, V4 cut it to 0.15s believing the threshold was taxing
    # walking — the reference is *higher* than either. Weight was 1.0, i.e. 4x
    # the reference. In every working config this is a mild regulariser; gait
    # emerges from velocity tracking against +-1.0 commands, not from here.
    feet_air_time = RewardTermCfg(
        func=gait_mdp.feet_air_time,
        weight=0.25,
        params={
            "command_name": "base_velocity",
            "sensor_cfg": SceneEntityCfg("contact_forces", body_names=".*_foot_link"),
            "threshold": 0.5,
        },
    )
    # The one term kept that Go2 flat doesn't have, sourced from
    # unitreerobotics/unitree_rl_lab's Go2 velocity task (-0.1, not the -0.25
    # V3-V5 used). Insurance against the glide this robot has repeatedly found;
    # the reference friction restored below should make it unnecessary, but it
    # is cheap and directly targets the known failure mode.
    feet_slide = RewardTermCfg(
        func=gait_mdp.feet_slide,
        weight=-0.1,
        params={
            "sensor_cfg": SceneEntityCfg("contact_forces", body_names=".*_foot_link"),
            "asset_cfg": SceneEntityCfg("robot", body_names=".*_foot_link"),
        },
    )
    # Thigh only, per the reference base config. V3-V5 also covered
    # .*_shin_link, which penalises the deep leg flexion a real gait needs —
    # a plausible contributor to the policy keeping its legs stiff and straight.
    # (Go2 disables this term outright; kept at the base config's -1.0 because
    # this robot has previously exploited crawling on its thighs.)
    undesired_contacts = RewardTermCfg(
        func=mdp.undesired_contacts,
        weight=-1.0,
        params={
            "sensor_cfg": SceneEntityCfg("contact_forces", body_names=".*_thigh_link"),
            "threshold": 1.0,
        },
    )


# ── Terminations ──────────────────────────────────────────────────────────────

@configclass
class TerminationsCfg:
    """Episode ends on timeout or if the body touches the ground."""

    time_out = TerminationTermCfg(func=mdp.time_out, time_out=True)

    # Body contact → robot has fallen
    base_contact = TerminationTermCfg(
        func=mdp.illegal_contact,
        params={
            "sensor_cfg": SceneEntityCfg("contact_forces", body_names="base_link"),
            "threshold": 1.0,
        },
    )


# ── Events (domain randomisation) ────────────────────────────────────────────

@configclass
class EventCfg:
    """
    Domain randomisation, aligned to the reference Go2 flat task.

    Go2 deliberately runs *less* randomisation than V3-V5 did: no joint-reset
    scaling, no COM offset, no pushes. That was worth knowing — the creep was
    never an under-exploration problem, so the V4 theory that over-hard
    randomisation "rewarded conservative wide stances" had it backwards too.
    The aggressive settings can come back for sim-to-real once a gait exists;
    they are noise while the base behaviour is still wrong.
    """

    # Fixed 0.8 static / 0.6 dynamic — the reference values, and the most
    # important change in this class. V3-V5 randomised over (0.4, 0.9): the
    # low end is an ice-like floor on which the planted-foot glide is nearly
    # free, so the environment itself was subsidising the failure mode.
    # Friction randomisation belongs back here for sim-to-real, but centred
    # well above 0.4.
    physics_material = EventTermCfg(
        func=mdp.randomize_rigid_body_material,
        mode="startup",
        params={
            "asset_cfg": SceneEntityCfg("robot", body_names=".*"),
            "static_friction_range": (0.8, 0.8),
            "dynamic_friction_range": (0.6, 0.6),
            "restitution_range": (0.0, 0.0),
            "num_buckets": 64,
        },
    )

    # Go2 uses (-1.0, 3.0) kg on a ~15 kg robot. Scaled to this ~5 kg body,
    # keeping the reference's asymmetry (payload is added far more often than
    # removed): -0.35 to +1.0 kg.
    add_base_mass = EventTermCfg(
        func=mdp.randomize_rigid_body_mass,
        mode="startup",
        params={
            "asset_cfg": SceneEntityCfg("robot", body_names="base_link"),
            "mass_distribution_params": (-0.35, 1.0),
            "operation": "add",
        },
    )

    # Reference base ranges: pose x/y +-0.5 and full yaw, all six velocity
    # components +-0.5. V3-V5 used roughly half this on the velocities.
    reset_base = EventTermCfg(
        func=mdp.reset_root_state_uniform,
        mode="reset",
        params={
            "pose_range": {"x": (-0.5, 0.5), "y": (-0.5, 0.5), "yaw": (-math.pi, math.pi)},
            "velocity_range": {
                "x": (-0.5, 0.5), "y": (-0.5, 0.5), "z": (-0.5, 0.5),
                "roll": (-0.5, 0.5), "pitch": (-0.5, 0.5), "yaw": (-0.5, 0.5),
            },
        },
    )

    # (1.0, 1.0) — Go2's override, i.e. every episode starts in the exact
    # default stance. V3-V5 scaled joint angles by (0.85, 1.15).
    reset_robot_joints = EventTermCfg(
        func=mdp.reset_joints_by_scale,
        mode="reset",
        params={"position_range": (1.0, 1.0), "velocity_range": (0.0, 0.0)},
    )

    # NOTE: Go2 disables `push_robot` and `base_com` randomisation entirely,
    # so both are absent here (V3-V5 had them). Re-add for balance robustness
    # and sim-to-real once a gait has actually emerged.


# ── Top-level environment config ──────────────────────────────────────────────

@configclass
class QuadrupedFlatEnvCfg(ManagerBasedRLEnvCfg):
    """
    Flat-terrain locomotion environment for the 5 kg quadruped.

    Key timing (all reference values):
      sim.dt      = 0.005 s  → physics at 200 Hz
      decimation  = 4        → policy runs at  50 Hz
      episode     = 20 s     → 1000 policy steps per episode
    """

    scene:        QuadrupedSceneCfg  = QuadrupedSceneCfg(num_envs=32, env_spacing=2.5)
    observations: ObservationsCfg   = ObservationsCfg()
    actions:      ActionsCfg        = ActionsCfg()
    commands:     CommandsCfg       = CommandsCfg()
    rewards:      RewardsCfg        = RewardsCfg()
    terminations: TerminationsCfg   = TerminationsCfg()
    events:       EventCfg          = EventCfg()

    def __post_init__(self) -> None:
        super().__post_init__()

        # Physics rate
        self.sim.dt = 0.005            # 200 Hz
        self.decimation = 4            # policy at 50 Hz
        self.episode_length_s = 20.0

        # Viewer camera angle (useful when not running headless)
        self.viewer.resolution = (1280, 720)
        self.viewer.eye = (3.5, 3.5, 2.5)
        self.viewer.lookat = (0.0, 0.0, 0.5)

        # Simulation settings
        self.sim.gravity = (0.0, 0.0, -9.81)
        self.sim.render_interval = self.decimation

        if self.scene.contact_forces is not None:
            self.scene.contact_forces.update_period = self.sim.dt
